language: python
dist: jammy
python:
  - 3.9

before_install:
  - sudo apt-get install graphviz graphviz-dev  # graphviz lib: https://pygraphviz.github.io/documentation/stable/install.html#ubuntu-and-debian
  - pip install -U setuptools  # for pygraphviz pip install: https://github.com/readthedocs/readthedocs.org/issues/9354#issuecomment-1160133066
  - pip install pytest codecov pytest-cov

install:
  - pip install ".[full,test]" . # install package + test dependencies

env:
  # This variable is required for Qt to work on CI.
  # https://gist.github.com/popzxc/70fe145a3a1109d5c11f7b2f06dd269f
  - QT_QPA_PLATFORM="offscreen"

script:
  - pytest --rootdir $TRAVIS_BUILD_DIR --cov=./ # run tests

after_success:
  - codecov
