language: python

python:
  - 3.9

before_install:
  - pip install pytest codecov pytest-cov

install:
  - pip install ".[full,test]" . # install package + test dependencies

env:
  # This variable is required for Qt to work on CI.
  # https://gist.github.com/popzxc/70fe145a3a1109d5c11f7b2f06dd269f
  - QT_QPA_PLATFORM="offscreen"

script:
  - pytest --rootdir $TRAVIS_BUILD_DIR --cov=./ # run tests

after_success:
  - codecov
